# Generated by Django 4.1.4 on 2022-12-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cursos', models.CharField(max_length=150)),
                ('Horas', models.DateField()),
            ],
        ),
    ]
